name: boxy-svg
title: Boxy SVG
adopt-info: electron-app
license: Proprietary
base: core20
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
    run-on: amd64
  - build-on: arm64
    run-on: arm64
  - build-on: armhf
    run-on: armhf
parts:
  electron-app:
    plugin: dump
    source: https://firebasestorage.googleapis.com/v0/b/boxy-svg.appspot.com/o/linux%2Fapp-3.85.0.zip?alt=media
    source-checksum: sha256/3caa9ee0602b2898678a2c6ce33ddab10a5d1a6651b3752289fa8d5a71eff95d
    source-type: zip
    parse-info: [app/metadata/com.boxy_svg.BoxySVG.appdata.xml]
    override-build: |
      # Bugfix: https://forum.snapcraft.io/t/problems-with-remote-build/24373/2
      if [ -z ${http_proxy+x} ];
      then
        echo "Not using proxy"
      else
        echo "Using proxy"
        export ELECTRON_GET_USE_PROXY=1
        export GLOBAL_AGENT_HTTP_PROXY="${http_proxy}"
        export GLOBAL_AGENT_HTTPS_PROXY="${http_proxy}"
        npm config set proxy $http_proxy
        npm config set https-proxy $https_proxy
      fi

      # Bugfix: Need to move the unarchived files manually because `source-subdir: app` does not seem to work
      cp -r ./app/* .

      # Install electron-builder and other dependencies from NPM
      npm install
      npm --prefix ./electron install

      # Generate linux-unpacked directory containing Electron binaries
      if [ ${SNAP_ARCH} = "armhf" ];
      then
        ./node_modules/.bin/electron-builder --armv7l
      else
        ./node_modules/.bin/electron-builder
      fi

      # Copy over the linux-unpacked directory contents
      mkdir -p $SNAPCRAFT_PART_INSTALL/opt/boxy-svg || true
      cp -ar ./dist/*-unpacked/* $SNAPCRAFT_PART_INSTALL/opt/boxy-svg/
    build-snaps:
      - node/14/stable
    build-packages:
      - build-essential
      - git
      - libfontconfig-dev
    stage-packages:
      - libappindicator3-1
      - libxss1
      - libnspr4
      - libnss3
      - libglu1-mesa
      - libnotify4
      - libnotify-bin
      - libpulse0
apps:
  boxy-svg:
    command: opt/boxy-svg/boxy-svg --no-sandbox
    common-id: com.boxy_svg.BoxySVG
    plugs:
      - desktop
      - desktop-legacy
      - home
      - removable-media
      - x11
      - unity7
      - wayland
      - browser-support
      - network
      - opengl
      - audio-playback
    extensions: [gnome-3-38]
    environment:
      DISABLE_WAYLAND: 1
      GTK_USE_PORTAL: 1
      TMPDIR: ${XDG_RUNTIME_DIR}
      PATH: ${SNAP}/usr/sbin:${SNAP}/usr/bin:${SNAP}/sbin:${SNAP}/bin:${PATH}
      SNAP_DESKTOP_RUNTIME: ${SNAP}/gnome-platform